name = "domba"
main = "src/index.js"
compatibility_date = "2025-09-01"

[vars]
# No plain-text API keys here. Use `wrangler secret put GEMINI_API_KEY`

name = "wisdom-cafe-worker"
# main = "worker.js" # This line is not needed for static site deployment
compatibility_date = "2025-09-20"

[site]
bucket = "."
